#!/usr/bin/env python3
"""Generate LaTeX tables from JEPA benchmark JSON results."""

from __future__ import annotations

import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
RESULTS = ROOT / "benchmarks/ml/results"
OUT = ROOT / "docs/paper/shared/tables/results.tex"

RUNS_MAIN = ["C0", "C1", "C2", "C3", "C4", "C5"]
RUNS_LABEL = ["C7", "C8", "C9"]
LABEL_PCT = {"C7": "10\\%", "C8": "25\\%", "C9": "50\\%"}

LABELS_EN = {
    "C0": "SE-ResNet scratch",
    "C1": "SE-ResNet ImageNet",
    "C2": "ResNet-50 + CNN-JEPA",
    "C3": "SE + CNN-JEPA (SE standard)",
    "C4": "SE + CNN-JEPA (SE mask-aware)",
    "C5": "SE + frozen teacher",
    "C7": "C4 @ 10\\% labels",
    "C8": "C4 @ 25\\% labels",
    "C9": "C4 @ 50\\% labels",
}


def load_run(run_id: str) -> dict | None:
    path = RESULTS / f"{run_id}_fold_simula_test.json"
    if not path.exists():
        return None
    return json.loads(path.read_text())


def polyp_recall(data: dict) -> float | None:
    names = data.get("class_names", [])
    cm = data.get("confusion_matrix")
    if not cm or "polyp" not in names:
        return None
    idx = names.index("polyp")
    row = cm[idx]
    total = sum(row)
    return row[idx] / total if total else 0.0


def fmt(x: float | None, digits: int = 3) -> str:
    return f"{x:.{digits}f}" if x is not None else "---"


def parse_per_class(report: str) -> dict[str, dict[str, float]]:
    out: dict[str, dict[str, float]] = {}
    for line in report.splitlines():
        m = re.match(
            r"\s*(landmark|normal_mucosa|polyp)\s+([\d.]+)\s+([\d.]+)\s+([\d.]+)\s+(\d+)",
            line,
        )
        if m:
            cls, prec, rec, f1, _ = m.groups()
            out[cls] = {"precision": float(prec), "recall": float(rec), "f1": float(f1)}
    return out


def main() -> None:
    lines = [
        "% Auto-generated by scripts/generate_paper_tables.py — do not edit by hand",
        "",
        "\\begin{table}[t]",
        "\\centering",
        "\\caption{Main benchmark comparison on the Simula fold (test split, $n=1433$).}",
        "\\label{tab:main}",
        "\\begin{tabular}{lcc}",
        "\\toprule",
        "Method & Macro-F1 & Polyp recall \\\\",
        "\\midrule",
    ]
    for run in RUNS_MAIN:
        data = load_run(f"{run}_fold_simula")
        if data is None:
            continue
        pr = polyp_recall(data)
        lines.append(
            f"{LABELS_EN[run]} & {fmt(data['macro_f1'])} & {fmt(pr)} \\\\"
        )
    lines.extend([
        "\\bottomrule",
        "\\end{tabular}",
        "\\end{table}",
        "",
        "\\begin{table}[t]",
        "\\centering",
        "\\caption{Label-efficiency curve for the proposed method (C4 backbone).}",
        "\\label{tab:labels}",
        "\\begin{tabular}{lcc}",
        "\\toprule",
        "Setting & Macro-F1 & Polyp recall \\\\",
        "\\midrule",
    ])
    c1 = load_run("C1_fold_simula")
    c4 = load_run("C4_fold_simula")
    if c1:
        lines.append(f"ImageNet (100\\% labels) & {fmt(c1['macro_f1'])} & {fmt(polyp_recall(c1))} \\\\")
    if c4:
        lines.append(f"C4 (100\\% labels) & {fmt(c4['macro_f1'])} & {fmt(polyp_recall(c4))} \\\\")
    for run in RUNS_LABEL:
        data = load_run(f"{run}_fold_simula")
        if data is None:
            continue
        lines.append(
            f"{LABELS_EN[run]} & {fmt(data['macro_f1'])} & {fmt(polyp_recall(data))} \\\\"
        )
    lines.extend([
        "\\bottomrule",
        "\\end{tabular}",
        "\\end{table}",
        "",
    ])

    c4_data = load_run("C4_fold_simula")
    if c4_data:
        per_class = parse_per_class(c4_data.get("classification_report", ""))
        lines.extend([
            "\\begin{table}[t]",
            "\\centering",
            "\\caption{Per-class metrics for C4 (SE + CNN-JEPA, mask-aware SE) on test.}",
            "\\label{tab:c4_perclass}",
            "\\begin{tabular}{lccc}",
            "\\toprule",
            "Class & Precision & Recall & F1 \\\\",
            "\\midrule",
        ])
        display = {
            "landmark": "Landmark",
            "normal_mucosa": "Normal mucosa",
            "polyp": "Polyp",
        }
        for cls, name in display.items():
            if cls in per_class:
                m = per_class[cls]
                lines.append(
                    f"{name} & {fmt(m['precision'])} & {fmt(m['recall'])} & {fmt(m['f1'])} \\\\"
                )
        lines.extend([
            "\\bottomrule",
            "\\end{tabular}",
            "\\end{table}",
            "",
        ])

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines))
    print(f"Wrote {OUT}")


if __name__ == "__main__":
    main()
