#!/usr/bin/env python3
"""Generate LaTeX tables from benchmark JSON results (T3 + T1)."""

from __future__ import annotations

import json
import re
import statistics
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
RESULTS = ROOT / "benchmarks/ml/results"
SEEDS_FILE = ROOT / "benchmarks/ml/seeds.json"
OUT = ROOT / "docs/paper/shared/tables/results.tex"

RUNS_MAIN = ["C0", "C1", "C2", "C3", "C4", "C5"]
RUNS_LABEL = ["C7", "C8", "C9"]

LABELS_EN = {
    "C0": "SE-ResNet scratch",
    "C1": "SE-ResNet ImageNet",
    "C2": "ResNet-50 + CNN-JEPA",
    "C3": "SE + CNN-JEPA (SE standard)",
    "C4": "SE + CNN-JEPA (SE mask-aware)",
    "C5": "SE + frozen teacher",
    "C7": "C4 @ 10\\% labels",
    "C8": "C4 @ 25\\% labels",
    "C9": "C4 @ 50\\% labels",
}

HK_RUNS = [
    ("B2", "hyperkvasir_b2_resnet50_imagenet", "ResNet-50", "ImageNet"),
    ("B3", "hyperkvasir_b3_seresnet50_scratch", "SE-ResNet-50", "scratch"),
    ("B4", "hyperkvasir_b4_seresnet50_imagenet", "SE-ResNet-50", "ImageNet"),
    ("B5", "hyperkvasir_b5_dualstream_scratch", "Dual-stream", "scratch"),
    ("B6", "hyperkvasir_b6_dualstream_imagenet", "Dual-stream", "ImageNet"),
]


def load_seeds() -> list[int]:
    if SEEDS_FILE.is_file():
        return json.loads(SEEDS_FILE.read_text())["seeds"]
    return [42]


def result_path(run_id: str, seed: int) -> Path:
    if seed == 42:
        legacy = RESULTS / f"{run_id}_fold_simula_test.json"
        if legacy.exists():
            return legacy
    return RESULTS / f"{run_id}_fold_simula_seed{seed}_test.json"


def load_run_runs(run_id: str) -> list[dict]:
    out: list[dict] = []
    for seed in load_seeds():
        path = result_path(run_id, seed)
        if path.is_file():
            out.append(json.loads(path.read_text()))
    return out


def load_run(run_id: str) -> dict | None:
    runs = load_run_runs(run_id)
    return runs[0] if runs else None


def load_hk(prefix: str) -> dict | None:
    path = RESULTS / f"{prefix}_test.json"
    if not path.exists():
        return None
    return json.loads(path.read_text())


def polyp_recall(data: dict) -> float | None:
    names = data.get("class_names", [])
    cm = data.get("confusion_matrix")
    if not cm:
        return None
    for cls in ("polyp", "polyps"):
        if cls in names:
            idx = names.index(cls)
            row = cm[idx]
            total = sum(row)
            return row[idx] / total if total else 0.0
    return None


def fmt(x: float | None, digits: int = 3) -> str:
    return f"{x:.{digits}f}" if x is not None else "---"


def fmt_mean_std(values: list[float], digits: int = 3) -> str:
    if not values:
        return "---"
    if len(values) == 1:
        return fmt(values[0], digits)
    mean = statistics.mean(values)
    std = statistics.stdev(values)
    return f"{mean:.{digits}f} $\\pm$ {std:.{digits}f}"


def metric_column(runs: list[dict], metric_fn) -> str:
    values = [v for r in runs if (v := metric_fn(r)) is not None]
    return fmt_mean_std(values)


def split_caption_note() -> str:
    manifest = ROOT / "data/colonoscopy_3class/manifest.json"
    seeds = load_seeds()
    seed_note = f"{len(seeds)} seeds" if len(seeds) > 1 else "single seed"
    if manifest.is_file():
        mode = json.loads(manifest.read_text()).get("split_mode", "unknown")
        return f"Group-aware split ({mode}); {seed_note}."
    return f"Stratified split; {seed_note}."


def parse_per_class(report: str) -> dict[str, dict[str, float]]:
    out: dict[str, dict[str, float]] = {}
    for line in report.splitlines():
        m = re.match(
            r"\s*(landmark|normal_mucosa|polyp)\s+([\d.]+)\s+([\d.]+)\s+([\d.]+)\s+(\d+)",
            line,
        )
        if m:
            cls, prec, rec, f1, _ = m.groups()
            out[cls] = {"precision": float(prec), "recall": float(rec), "f1": float(f1)}
    return out


def main() -> None:
    caption_note = split_caption_note()
    lines = [
        "% Auto-generated by scripts/generate_paper_tables.py — do not edit by hand",
        "",
        "\\begin{table}[t]",
        "\\centering",
        f"\\caption{{Three-class screening (T3) on Simula test split ($n=1433$). {caption_note}}}",
        "\\label{tab:main}",
        "\\begin{tabular}{lcc}",
        "\\toprule",
        "Method & Macro-F1 & Polyp recall \\\\",
        "\\midrule",
    ]
    for run in RUNS_MAIN:
        runs = load_run_runs(run)
        if not runs:
            continue
        lines.append(
            f"{LABELS_EN[run]} & {metric_column(runs, lambda r: r['macro_f1'])} "
            f"& {metric_column(runs, polyp_recall)} \\\\"
        )
    lines.extend([
        "\\bottomrule",
        "\\end{tabular}",
        "\\end{table}",
        "",
        "\\begin{table}[t]",
        "\\centering",
        "\\caption{Label-efficiency curve for C4 (mask-aware SE + CNN-JEPA).}",
        "\\label{tab:labels}",
        "\\begin{tabular}{lcc}",
        "\\toprule",
        "Setting & Macro-F1 & Polyp recall \\\\",
        "\\midrule",
    ])
    c1_runs = load_run_runs("C1")
    c4_runs = load_run_runs("C4")
    if c1_runs:
        lines.append(
            f"ImageNet (100\\% labels) & {metric_column(c1_runs, lambda r: r['macro_f1'])} "
            f"& {metric_column(c1_runs, polyp_recall)} \\\\"
        )
    if c4_runs:
        lines.append(
            f"C4 (100\\% labels) & {metric_column(c4_runs, lambda r: r['macro_f1'])} "
            f"& {metric_column(c4_runs, polyp_recall)} \\\\"
        )
    for run in RUNS_LABEL:
        runs = load_run_runs(run)
        if not runs:
            continue
        lines.append(
            f"{LABELS_EN[run]} & {metric_column(runs, lambda r: r['macro_f1'])} "
            f"& {metric_column(runs, polyp_recall)} \\\\"
        )
    lines.extend([
        "\\bottomrule",
        "\\end{tabular}",
        "\\end{table}",
        "",
        "\\begin{table}[t]",
        "\\centering",
        "\\caption{HyperKvasir 23-class supervised baselines (T1, test split). Prior work on this dataset reports macro-F1 $\\approx$0.55--0.60 for ResNet-style fine-tuning.}",
        "\\label{tab:hk23}",
        "\\begin{tabular}{lllcc}",
        "\\toprule",
        "Run & Architecture & Pretrain & Macro-F1 & Acc. \\\\",
        "\\midrule",
    ])
    for run_id, prefix, arch, pt in HK_RUNS:
        data = load_hk(prefix)
        if not data:
            continue
        lines.append(
            f"{run_id} & {arch} & {pt} & {fmt(data.get('macro_f1'))} & {fmt(data.get('accuracy'))} \\\\"
        )
    lines.extend([
        "\\bottomrule",
        "\\end{tabular}",
        "\\end{table}",
        "",
    ])

    c4_data = load_run("C4")
    if c4_data:
        per_class = parse_per_class(c4_data.get("classification_report", ""))
        lines.extend([
            "\\begin{table}[t]",
            "\\centering",
            "\\caption{Per-class metrics for C4 on T3 test.}",
            "\\label{tab:c4_perclass}",
            "\\begin{tabular}{lccc}",
            "\\toprule",
            "Class & Precision & Recall & F1 \\\\",
            "\\midrule",
        ])
        for cls, name in [
            ("landmark", "Landmark"),
            ("normal_mucosa", "Normal mucosa"),
            ("polyp", "Polyp"),
        ]:
            if cls in per_class:
                m = per_class[cls]
                lines.append(f"{name} & {fmt(m['precision'])} & {fmt(m['recall'])} & {fmt(m['f1'])} \\\\")
        lines.extend([
            "\\bottomrule",
            "\\end{tabular}",
            "\\end{table}",
            "",
        ])

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines))
    print(f"Wrote {OUT}")


if __name__ == "__main__":
    main()
